// <auto-generated />
using System;
using Kirel.Logger.Messages.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kirel.Logger.Messages.API.Migrations.Mysql
{
    [DbContext(typeof(KirelLogMysqlMessageContext))]
    partial class KirelLogMysqlMessageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kirel.Logger.Messages.API.Models.KirelLogMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("InnerExceptionMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("Level")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Service")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Service", "Source", "Level");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
