#!/bin/bash

for dir in */; do 
    cd "$dir";
    projectName="${dir::-1}"
    if [ -f "Dockerfile" ]; then
        echo -e "\033[0;36mStarting build \033[1;36m"${projectName,,}" \033[0;36mdocker image...\033[0m"
        docker build -t "${projectName,,}":latest -f Dockerfile ../
    fi
    cd ../;
done
